#!/usr/bin/env bash
# Smart, per-machine installer for the silverware-drawer spoon collection.
#
# Presents an fzf multi-picker of the available spoons, symlinks the selected
# ones into Hammerspoon, and writes a per-machine config the loader reads. The
# repo is shared across machines; the selection lives outside the repo so each
# machine keeps its own set.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SPOONS_SRC="$REPO/spoons"
HS_DIR="$HOME/.hammerspoon"
SPOON_DST_DIR="$HS_DIR/Spoons"
CONFIG="$HS_DIR/silverware-drawer.config.lua"
LOADER_DST="$HS_DIR/silverware-drawer.lua"
INIT="$HS_DIR/init.lua"
REQUIRE_LINE='require("silverware-drawer")'

if ! command -v fzf >/dev/null 2>&1; then
  echo "error: fzf is required but not found on PATH." >&2
  echo "       install it (e.g. 'brew install fzf') and re-run." >&2
  exit 1
fi

# --- discover spoons -------------------------------------------------------
# Read a one-line description from each spoon's '--- === Name ===' header: the
# first prose '--- ...' line that isn't the title banner.
spoon_desc() {
  grep -m1 -E '^--- [^=]' "$1/init.lua" 2>/dev/null | sed -E 's/^--- //' || true
}

declare -a NAMES=()
for dir in "$SPOONS_SRC"/*.spoon; do
  [ -d "$dir" ] || continue
  NAMES+=("$(basename "$dir" .spoon)")
done

if [ "${#NAMES[@]}" -eq 0 ]; then
  echo "error: no spoons found in $SPOONS_SRC" >&2
  exit 1
fi

# --- currently-enabled set (for display markers) ---------------------------
currently_enabled() {
  [ -f "$CONFIG" ] || return 0
  # Pull bare names and name= entries out of the Lua config.
  grep -oE '"[A-Za-z0-9_]+"|name *= *"[A-Za-z0-9_]+"' "$CONFIG" \
    | grep -oE '"[A-Za-z0-9_]+"' | tr -d '"' | sort -u
}
ENABLED_BEFORE="$(currently_enabled || true)"

is_enabled() { grep -qxF "$1" <<<"$ENABLED_BEFORE"; }

# --- build picker lines ----------------------------------------------------
# Format: "Name\t● description" — Name is field 1 (hidden), rest is shown.
picker_input() {
  local name desc marker
  for name in "${NAMES[@]}"; do
    desc="$(spoon_desc "$SPOONS_SRC/$name")"
    if is_enabled "$name"; then marker="●"; else marker="○"; fi
    printf '%s\t%s %s — %s\n' "$name" "$marker" "$name" "$desc"
  done
}

echo "Select spoons to enable on this machine (TAB to toggle, Enter to confirm)."
echo "  ● = currently enabled, ○ = not enabled"
SELECTED="$(picker_input | fzf --multi --with-nth=2.. --delimiter='\t' \
  --prompt='spoons> ' --header='TAB: toggle  ENTER: confirm  ESC: cancel' \
  --no-sort | cut -f1 || true)"

if [ -z "$SELECTED" ]; then
  read -r -p "No spoons selected — disable all on this machine? [y/N] " ans
  [[ "$ans" =~ ^[Yy]$ ]] || { echo "Aborted; nothing changed."; exit 0; }
fi

# --- apply symlinks --------------------------------------------------------
mkdir -p "$SPOON_DST_DIR"

# Remove symlinks for previously-enabled spoons that point into this repo
# (so deselecting actually unlinks). Never touch unrelated/real spoons.
while IFS= read -r name; do
  [ -n "$name" ] || continue
  link="$SPOON_DST_DIR/$name.spoon"
  if [ -L "$link" ] && [[ "$(readlink "$link")" == "$SPOONS_SRC/"* ]]; then
    rm -f "$link"
  fi
done <<<"$ENABLED_BEFORE"

# Symlink selected spoons.
while IFS= read -r name; do
  [ -n "$name" ] || continue
  src="$SPOONS_SRC/$name.spoon"
  dst="$SPOON_DST_DIR/$name.spoon"
  rm -rf "$dst"
  ln -s "$src" "$dst"
  echo "✓ linked $name"
done <<<"$SELECTED"

# --- write per-machine config ----------------------------------------------
{
  echo "-- Generated by silverware-drawer install.sh — per machine, do not commit."
  echo "-- Re-run ./install.sh to change the enabled set."
  echo "return {"
  while IFS= read -r name; do
    [ -n "$name" ] || continue
    echo "  \"$name\","
  done <<<"$SELECTED"
  echo "}"
} >"$CONFIG"
echo "✓ wrote $CONFIG"

# --- loader symlink + init.lua line ----------------------------------------
rm -f "$LOADER_DST"
ln -s "$REPO/load.lua" "$LOADER_DST"
echo "✓ linked loader -> $LOADER_DST"

if [ -f "$INIT" ]; then
  if grep -qF "$REQUIRE_LINE" "$INIT"; then
    : # already present
  else
    printf '\n%s\n' "$REQUIRE_LINE" >>"$INIT"
    echo "✓ added '$REQUIRE_LINE' to $INIT"
  fi
else
  echo
  echo "No $INIT found. Create it with this line:"
  echo "    $REQUIRE_LINE"
fi

# --- reload ----------------------------------------------------------------
echo
if command -v hs >/dev/null 2>&1; then
  hs -c "hs.reload()" >/dev/null 2>&1 && echo "✓ reloaded Hammerspoon" || \
    echo "Reload Hammerspoon to apply (Hammerspoon menu → Reload Config)."
else
  echo "Reload Hammerspoon to apply (Hammerspoon menu → Reload Config)."
fi
